### PR TITLE
Add --no-skip/-n flag

### PR DESCRIPTION
**Pull request by bkhl**
Added flag to ignore skipping of tests.

Possible implementation of sstephenson/bats#264

### CODE REVIEW

**Comment by guygastineau** [comment]
Any word on fixes to get this passing the CI build?

**Comment by bkhl** [comment]
No, just that I hope to have time for a look at it this weekend.

**Comment by guygastineau** [comment]
Thank you for the update.

**Comment by bkhl** [comment]
Closed as the main branch of this project is now in https://github.com/bats-core/bats-core, and it seems this change may not be applicable anymore.

**Pull request closed without merging**
